### ISSUE TITLE
Avoid dashes for native elements.

### ISSUE THREAD

**Issue by trusktr** [fergald/virtual-scroller-demos#7]
I believe that built-in elements should not have dashes in the name. So maybe it would need to be something like:

```html
<virtualscroller ... />
```

What I've decided to do when I "polyfill" an element that I'd like to propose as a native element is to append a hyphen to it, f.e.

```html
<virtualscroller- ... />
```

which is valid for custom element naming for the polyfill.

**Comment by fergald** [comment]
Thanks. This project is currently paused.
